-- migrations/0003_seed.sql
-- Generated by scripts/json-to-seed.js from data/project-data.json.
-- Do not hand-edit; re-run `npm run seed` to regenerate.
-- updated_by / created_by = 'seed' marks the original import.

-- dev / SchoolTRAK
INSERT INTO projects (id, "group", name, status, status_class, stage, stage_class, statusline, what_it_is, next_step, sort, updated_by) VALUES
  (1, 'dev', 'SchoolTRAK', 'In Progress', 'info', 'Dev', 'dev', 'Cruxlab working SOW items (smaller first); period-rules (ITM 14) redesign finalized, awaiting specifics to the dev team.', 'STA''s attendance / period-management product, built with the Cruxlab team (Maryna, Oleg); Chris Baker is STA owner.', NULL, 0, 'seed');
INSERT INTO open_items (id, project_id, text, stage, stage_class, meta, sort, updated_by) VALUES
  (1, 1, 'GitHub access for Oleg Rakhov', 'Dev', 'dev', 'Chris Â· overdue 5/29', 0, 'seed');
INSERT INTO open_items (id, project_id, text, stage, stage_class, meta, sort, updated_by) VALUES
  (2, 1, 'Year/rollover warning corner notification', 'Dev', 'dev', 'dev team', 1, 'seed');
INSERT INTO open_items (id, project_id, text, stage, stage_class, meta, sort, updated_by) VALUES
  (3, 1, 'Finalize Period Rules (ITM 14) redesign + send specifics', 'Dev', 'dev', 'Andrew / Chris', 2, 'seed');
INSERT INTO open_items (id, project_id, text, stage, stage_class, meta, sort, updated_by) VALUES
  (4, 1, 'Test build for Chris to deploy/test', 'Dev', 'dev', 'dev team', 3, 'seed');
INSERT INTO open_items (id, project_id, text, stage, stage_class, meta, sort, updated_by) VALUES
  (5, 1, 'Review Wisconsin Rapids QOL feedback (live product)', 'Post-Release', 'post', 'Chris', 4, 'seed');
INSERT INTO stage_history (id, project_id, when_label, note, created_by) VALUES
  (1, 1, 'Dev Â· 2025 â†’ now', 'Active feature dev via SOW (current).', 'seed');
INSERT INTO stage_history (id, project_id, when_label, note, created_by) VALUES
  (2, 1, 'Prelim / earlier Dev', 'Start dates reconstructed in Tanya''s 2024-2025 cleanup; recorded going forward.', 'seed');
INSERT INTO timeline (id, project_id, when_label, note, created_by) VALUES
  (1, 1, '5/29', 'Sprint shipped: show-password, single-entity auto-select, teacher name across templates.', 'seed');
INSERT INTO timeline (id, project_id, when_label, note, created_by) VALUES
  (2, 1, '6/4', 'Period-rules redesign finalized (in SOW), awaiting dev specifics.', 'seed');

-- dev / TimeClock App / Gone for the Day
INSERT INTO projects (id, "group", name, status, status_class, stage, stage_class, statusline, what_it_is, next_step, sort, updated_by) VALUES
  (2, 'dev', 'TimeClock App / Gone for the Day', 'RC in Skyward QA', 'warn', 'Dev', 'dev', 'Release candidate in Skyward QA. "Gone for the Day" nearly done (CMI fixing edit-timesheet). Portal complete, held for coordinated release.', 'STA time-clock application / Virtual Kiosk; dev with Cruxlab (Vladimir); CMI is the hardware partner.', NULL, 1, 'seed');
INSERT INTO open_items (id, project_id, text, stage, stage_class, meta, sort, updated_by) VALUES
  (6, 2, 'Share RC + test-user info + activation code', 'Dev', 'dev', 'Vladimir', 0, 'seed');
INSERT INTO open_items (id, project_id, text, stage, stage_class, meta, sort, updated_by) VALUES
  (7, 2, 'Skyward QA: test RC + return feedback', 'Dev', 'dev', 'Skyward QA (external)', 1, 'seed');
INSERT INTO open_items (id, project_id, text, stage, stage_class, meta, sort, updated_by) VALUES
  (8, 2, 'CMI: fix edit-timesheet issue (Gone for the Day)', 'Dev', 'dev', 'CMI', 2, 'seed');
INSERT INTO open_items (id, project_id, text, stage, stage_class, meta, sort, updated_by) VALUES
  (9, 2, 'Coordinate release date with Cody before rollout', 'no stage', 'none', 'Adam Â· release ops', 3, 'seed');
INSERT INTO stage_history (id, project_id, when_label, note, created_by) VALUES
  (3, 2, 'Dev Â· through 2026', 'Pre-release; RC currently in QA. Not yet shipped, so all current work is Dev.', 'seed');
INSERT INTO timeline (id, project_id, when_label, note, created_by) VALUES
  (3, 2, '5/21-5/28', 'Status + job-switching fixes (status buttons reduced to 6).', 'seed');
INSERT INTO timeline (id, project_id, when_label, note, created_by) VALUES
  (4, 2, '6/4', 'RC shared with Skyward QA; self-service portal complete, held for coordinated release.', 'seed');

-- dev / VirtuaTime
INSERT INTO projects (id, "group", name, status, status_class, stage, stage_class, statusline, what_it_is, next_step, sort, updated_by) VALUES
  (3, 'dev', 'VirtuaTime', 'Out of beta / Maintenance', 'ok', 'Post-Release', 'post', 'Out of beta; PWA docs ready (Chromebook-optimized). One Apple-account complication remains before full rollout.', 'STA time product, now post-beta in maintenance; ready for market.', NULL, 2, 'seed');
INSERT INTO open_items (id, project_id, text, stage, stage_class, meta, sort, updated_by) VALUES
  (10, 3, 'Discuss added dev cost for Apple-account issue (existing-customer enablement)', 'Post-Release', 'post', 'Andrew (with Kost)', 0, 'seed');
INSERT INTO open_items (id, project_id, text, stage, stage_class, meta, sort, updated_by) VALUES
  (11, 3, 'Finish portal rollout documentation', 'no stage', 'none', 'docs / ops', 1, 'seed');
INSERT INTO stage_history (id, project_id, when_label, note, created_by) VALUES
  (4, 3, 'Dev â†’ beta', 'Feature build through beta.', 'seed');
INSERT INTO stage_history (id, project_id, when_label, note, created_by) VALUES
  (5, 3, 'Post-Release Â· 2026 â†’ now', 'Out of beta; maintenance + customer-enablement work.', 'seed');
INSERT INTO timeline (id, project_id, when_label, note, created_by) VALUES
  (5, 3, '6/4', 'Confirmed maintenance phase; Apple-account complication flagged.', 'seed');

-- ops / ID Product (Brian's)
INSERT INTO projects (id, "group", name, status, status_class, stage, stage_class, statusline, what_it_is, next_step, sort, updated_by) VALUES
  (4, 'ops', 'ID Product (Brian''s)', 'Evaluation', 'info', NULL, NULL, 'Evaluating Brian''s ID product; need a live demo before deciding on a monthly subscription model. Vidix competition is a concern.', NULL, NULL, 3, 'seed');
INSERT INTO open_items (id, project_id, text, stage, stage_class, meta, sort, updated_by) VALUES
  (12, 4, 'Andrew: see the product + discuss non-compete', NULL, NULL, '', 0, 'seed');
INSERT INTO open_items (id, project_id, text, stage, stage_class, meta, sort, updated_by) VALUES
  (13, 4, 'Andrew: meet Dave re Skyward''s approach', NULL, NULL, '', 1, 'seed');
INSERT INTO open_items (id, project_id, text, stage, stage_class, meta, sort, updated_by) VALUES
  (14, 4, 'Chris: meet the ID team next week', NULL, NULL, '', 2, 'seed');
INSERT INTO open_items (id, project_id, text, stage, stage_class, meta, sort, updated_by) VALUES
  (15, 4, '(Tentative) Adam: install ID software for Wednesday''s meeting if no new ID sales progress', NULL, NULL, '', 3, 'seed');

-- ops / ID Badging (STA)
INSERT INTO projects (id, "group", name, status, status_class, stage, stage_class, statusline, what_it_is, next_step, sort, updated_by) VALUES
  (5, 'ops', 'ID Badging (STA)', 'Active', 'info', NULL, NULL, 'Exploring a monthly billing / hardware-as-a-service model for the ID Badging line. Distinct from Brian''s ID product.', NULL, NULL, 4, 'seed');
INSERT INTO open_items (id, project_id, text, stage, stage_class, meta, sort, updated_by) VALUES
  (16, 5, 'Explore monthly billing / hardware-as-a-service model', NULL, NULL, 'team', 0, 'seed');

-- ops / Skyward Partnership & Lead Gen
INSERT INTO projects (id, "group", name, status, status_class, stage, stage_class, statusline, what_it_is, next_step, sort, updated_by) VALUES
  (6, 'ops', 'Skyward Partnership & Lead Gen', 'In Progress', 'info', NULL, NULL, 'Lead-gen off SEC-form migration signals; positive-attendance positioning with Skyward; first quarterly leadership call July 13.', NULL, 'First quarterly Skyward leadership call - July 13 @ 1:00 PM.', 5, 'seed');
INSERT INTO open_items (id, project_id, text, stage, stage_class, meta, sort, updated_by) VALUES
  (17, 6, 'Andrew: follow up with Diego on SchoolTRAK lead gen', NULL, NULL, '', 0, 'seed');
INSERT INTO open_items (id, project_id, text, stage, stage_class, meta, sort, updated_by) VALUES
  (18, 6, 'Lead-gen via SEC-form review (schools moving on-prem to cloud); leverage IS Corp migration', NULL, NULL, '', 1, 'seed');
INSERT INTO open_items (id, project_id, text, stage, stage_class, meta, sort, updated_by) VALUES
  (19, 6, 'Andrew: discuss PA approach + SIS-leaving trend with Dave Ilka', NULL, NULL, '', 2, 'seed');

-- ops / Podcast (Behind the Bell)
INSERT INTO projects (id, "group", name, status, status_class, stage, stage_class, statusline, what_it_is, next_step, sort, updated_by) VALUES
  (7, 'ops', 'Podcast (Behind the Bell)', 'In Progress', 'info', NULL, NULL, 'Episode 1 (Jared) is live; Episode 5 after Rachel returns; "Heady" episode targeting September (Attendance Awareness Month).', NULL, NULL, 6, 'seed');
INSERT INTO open_items (id, project_id, text, stage, stage_class, meta, sort, updated_by) VALUES
  (20, 7, 'Andy: send podcast blog post Google doc to Megan', NULL, NULL, '', 0, 'seed');

-- ops / CMI TT3 hardware
INSERT INTO projects (id, "group", name, status, status_class, stage, stage_class, statusline, what_it_is, next_step, sort, updated_by) VALUES
  (8, 'ops', 'CMI TT3 hardware', 'In stock ~1-2 wks', 'ok', NULL, NULL, 'CMI TT3s back in stock within 1-2 weeks - shorter shipping times for sales. Informational.', NULL, NULL, 7, 'seed');

