-- DRAFT - migrations/0014_tracker_v1_init.sql
-- Projects tab v1 redesign schema. DRAFT ONLY - lives in future-enhancements/
-- so wrangler cannot apply it by accident. Copy into migrations/ when PT1 builds.
--
-- Encodes the 2026-07-23 decision of record + its 2026-08-12 post-audit addendum
-- (D1-D8), and matches projects-tab-redesign-mockup.html v4 field for field.
--
-- Additive only. The Phase-A tables (projects, open_items, stage_history, timeline)
-- are left untouched so the live read-only Projects tab keeps rendering until the
-- new front end lands. Their retirement is a separate later migration - see the
-- FK warning at the bottom of this file.
--
-- Conventions (per KB module-01, matching 0001_init.sql and 0005_briefing_init.sql):
--   - integer surrogate keys
--   - all timestamps stored as ISO-8601 UTC TEXT; plain dates as YYYY-MM-DD TEXT
--   - version / updated_at / updated_by on every mutable row
--   - soft delete via deleted_at (NULL = live)
--   - append-only event tables carry no version column

PRAGMA foreign_keys = ON;

-- ---------------------------------------------------------------------------
-- Lookups
-- ---------------------------------------------------------------------------

-- The seven board sections: four persistent product lines plus the three
-- non-product homes. kind drives the section styling and the "no single home"
-- routing rule; it is not a status.
CREATE TABLE tr_sections (
  id          INTEGER PRIMARY KEY,
  key         TEXT NOT NULL UNIQUE,                 -- schooltrak | virtuatime | timeclocks | idbadging | cross | standalone | ops
  name        TEXT NOT NULL,
  kind        TEXT NOT NULL CHECK (kind IN ('product','cross','standalone','ops')),
  blurb       TEXT NOT NULL DEFAULT '',             -- the small grey line in the section header
  sort        INTEGER NOT NULL DEFAULT 0,
  version     INTEGER NOT NULL DEFAULT 1,
  created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_by  TEXT NOT NULL DEFAULT 'system',
  deleted_at  TEXT
);

-- Assignee picklist. Native per the 2026-07-23 reversal - NOT sourced from
-- Salesforce. Drives the assignee filter chips; expandable without a migration.
CREATE TABLE tr_people (
  id          INTEGER PRIMARY KEY,
  key         TEXT NOT NULL UNIQUE,                 -- adam | chris | tyler | pat | dan | andy | tanya
  name        TEXT NOT NULL,
  email       TEXT,                                 -- Access identity when known; NULL otherwise
  active      INTEGER NOT NULL DEFAULT 1,           -- 0 hides them from the picker without losing history
  sort        INTEGER NOT NULL DEFAULT 0,
  version     INTEGER NOT NULL DEFAULT 1,
  created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_by  TEXT NOT NULL DEFAULT 'system',
  deleted_at  TEXT
);

CREATE TABLE tr_vendors (
  id          INTEGER PRIMARY KEY,
  name        TEXT NOT NULL UNIQUE,                 -- Crux | CMI | Skyward | Ban-Koe
  sort        INTEGER NOT NULL DEFAULT 0,
  version     INTEGER NOT NULL DEFAULT 1,
  created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_by  TEXT NOT NULL DEFAULT 'system',
  deleted_at  TEXT
);

-- ---------------------------------------------------------------------------
-- The core entity
-- ---------------------------------------------------------------------------

-- One row per work item. section_id is the item's ONE home section (D2) - a
-- cross-product item renders there and nowhere else, with its also-affects tags
-- visible. Waiting-on and Blocked are FLAGS on this row, never statuses (D1).
CREATE TABLE tr_items (
  id                INTEGER PRIMARY KEY,
  -- Stable human id (st-reunif, tc-chips). Deep links + idempotent reseed.
  -- Auto-generated by the API on create and IMMUTABLE thereafter: retitling an
  -- item never changes its slug, or every saved link to it breaks.
  -- Rule: prefix + first words of the title. Prefix is 'fr-' for feature
  -- requests, otherwise the section code (st/vt/tc/id/x/sa/op). Collisions get
  -- -2, -3. This reproduces all 27 seeded slugs exactly.
  slug              TEXT NOT NULL UNIQUE,
  section_id        INTEGER NOT NULL REFERENCES tr_sections(id),
  module            TEXT,                           -- sub-label within a section ("Positive Attendance"); NULL = none
  type              TEXT NOT NULL CHECK (type IN ('bug','feature','newproduct','decision','request')),
  title             TEXT NOT NULL,

  -- Status: four values, nothing else. Canceled is off-flow (D5).
  status            TEXT NOT NULL CHECK (status IN ('open','prog','done','canc')),
  -- Set ONLY on a real status transition (D4). Never touched by an unrelated edit.
  -- YYYY-MM-DD like the two flag stamps: all three ages are displayed in whole
  -- days, and day granularity keeps the seed honest where only the day is known.
  status_changed_at TEXT,

  -- Feature-request lifecycle. On-Hold and Archived leave the active board (D5).
  req_state         TEXT CHECK (req_state IS NULL OR req_state IN ('requested','onhold','archived')),

  assignee_id       INTEGER REFERENCES tr_people(id),
  target_date       TEXT,                           -- YYYY-MM-DD, optional, one per item (D3)

  -- Off-flow flag 1: waiting on a named party. Parallel to status, not a status.
  waiting_who       TEXT CHECK (waiting_who IS NULL OR waiting_who IN ('schooltech','vendor','customer')),
  waiting_since     TEXT,                           -- YYYY-MM-DD; the dashboard ages from THIS, never from updated_at
  waiting_note      TEXT,

  -- Off-flow flag 2: blocked, cannot proceed at all.
  blocked_on        TEXT,
  blocked_since     TEXT,                           -- YYYY-MM-DD; ages independently of waiting_since

  -- R&D stage: in the schema, hidden in v1, Stage 4 (Meetings) deliberately
  -- excluded because it classifies time entries, not items (D7).
  stage             TEXT CHECK (stage IS NULL OR stage IN ('prelim','dev','post')),
  -- Operations/Internal split-by-department, hidden until the section grows.
  department        TEXT,

  sort              INTEGER NOT NULL DEFAULT 0,
  version           INTEGER NOT NULL DEFAULT 1,
  created_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_by        TEXT NOT NULL DEFAULT 'system',
  deleted_at        TEXT,

  -- A flag without its own since date is the bug finding 5 described: an age
  -- that has to fall back on updated_at. Make it unrepresentable.
  CHECK ((waiting_who IS NULL AND waiting_since IS NULL)
      OR (waiting_who IS NOT NULL AND waiting_since IS NOT NULL)),
  CHECK ((blocked_on IS NULL AND blocked_since IS NULL)
      OR (blocked_on IS NOT NULL AND blocked_since IS NOT NULL)),
  -- req_state belongs to feature requests only.
  CHECK ((type = 'request' AND req_state IS NOT NULL)
      OR (type <> 'request' AND req_state IS NULL))
);

-- Also-affects tags (D2). Many-to-many over containment, per Module 1 SSOT:
-- one item record, referenced from every product it touches, never duplicated.
-- The home section is tr_items.section_id and is NOT repeated here.
CREATE TABLE tr_item_products (
  item_id     INTEGER NOT NULL REFERENCES tr_items(id) ON DELETE CASCADE,
  section_id  INTEGER NOT NULL REFERENCES tr_sections(id),
  PRIMARY KEY (item_id, section_id)
);

CREATE TABLE tr_item_vendors (
  item_id     INTEGER NOT NULL REFERENCES tr_items(id) ON DELETE CASCADE,
  vendor_id   INTEGER NOT NULL REFERENCES tr_vendors(id),
  PRIMARY KEY (item_id, vendor_id)
);

-- One level of checklist per item. Deliberately NOT a second hierarchy: no
-- assignee, no dates, no status - the escape valve is promotion (finding 10).
-- A promoted sub-item is soft-deleted and keeps a pointer to the item it became,
-- so the trail survives.
CREATE TABLE tr_subitems (
  id                INTEGER PRIMARY KEY,
  item_id           INTEGER NOT NULL REFERENCES tr_items(id) ON DELETE CASCADE,
  text              TEXT NOT NULL,
  done              INTEGER NOT NULL DEFAULT 0,
  done_at           TEXT,
  promoted_item_id  INTEGER REFERENCES tr_items(id),   -- set when this row was promoted out
  sort              INTEGER NOT NULL DEFAULT 0,
  version           INTEGER NOT NULL DEFAULT 1,
  created_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_by        TEXT NOT NULL DEFAULT 'system',
  deleted_at        TEXT
);

-- Explicit dependency links (the KB's stated companion to a blocked flag).
-- Direction: item_id depends on depends_on_id - "Full reunification depends on
-- Positive Attendance". The reverse view ("Required by") is DERIVED, never stored.
-- qualifier carries the real-world condition, e.g. 'Full only'.
CREATE TABLE tr_dependencies (
  item_id        INTEGER NOT NULL REFERENCES tr_items(id) ON DELETE CASCADE,
  depends_on_id  INTEGER NOT NULL REFERENCES tr_items(id) ON DELETE CASCADE,
  qualifier      TEXT,
  created_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  created_by     TEXT NOT NULL DEFAULT 'system',
  PRIMARY KEY (item_id, depends_on_id),
  CHECK (item_id <> depends_on_id)
);

-- Per-item change history, collapsed by default in the UI (2026-07-23 decision).
-- Append-only, so no version column - nobody edits a historical line.
-- when_label is the free-text stamp the seed carries ("Jul 24"); occurred_on is
-- the machine date where one is known.
CREATE TABLE tr_history (
  id          INTEGER PRIMARY KEY,
  item_id     INTEGER NOT NULL REFERENCES tr_items(id) ON DELETE CASCADE,
  when_label  TEXT NOT NULL DEFAULT '',
  occurred_on TEXT,                                  -- YYYY-MM-DD when known, else NULL
  note        TEXT NOT NULL,
  sort        INTEGER NOT NULL DEFAULT 0,
  created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  created_by  TEXT NOT NULL DEFAULT 'system'
);

-- Attribution reuses the existing audit table from 0001_init.sql.
-- entity_type values added by this schema: tr_item | tr_subitem | tr_dependency.
-- No new audit table.

-- ---------------------------------------------------------------------------
-- FK warning for the later retirement migration
-- ---------------------------------------------------------------------------
-- briefing_project_refs.project_id is a FK to projects(id) (0005_briefing_init).
-- Dropping the Phase-A projects table therefore cannot happen on its own: the
-- retirement migration must first repoint briefing_project_refs at tr_items (or
-- null the column out) or the My Day tab's project refs break. Do not fold that
-- into the PT1 deploy.
