// scripts/json-to-seed.js
// One-time, reproducible seed: read data/project-data.json and emit
// migrations/0003_seed.sql as parameter-free INSERTs (updated_by/created_by =
// 'seed' so provenance is obvious). Single quotes are escaped by doubling.
//
// Re-runnable: regenerates the .sql deterministically (explicit ids, global sort
// order) so re-running before the migration is applied just rewrites the file.
//
// Usage:
//   node scripts/json-to-seed.js                  # repo data/ -> migrations/
//   node scripts/json-to-seed.js <in.json> <out.sql>
//
// IMPORTANT: writes the file itself as UTF-8. Do NOT pipe via PowerShell `>`,
// which would produce UTF-16 and corrupt the multi-byte characters in the data.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "..");

const inPath = process.argv[2]
  ? resolve(process.argv[2])
  : resolve(repoRoot, "data", "project-data.json");
const outPath = process.argv[3]
  ? resolve(process.argv[3])
  : resolve(repoRoot, "migrations", "0003_seed.sql");

// SQL literal for a possibly-null string. Returns NULL (unquoted) for null/undefined.
const s = (v) => (v == null ? "NULL" : `'${String(v).replace(/'/g, "''")}'`);
// SQL literal for a non-null string column (empty string allowed).
const sReq = (v) => `'${String(v ?? "").replace(/'/g, "''")}'`;

function build(data) {
  const groups = data.groups || [];
  const lines = [];
  lines.push("-- migrations/0003_seed.sql");
  lines.push("-- Generated by scripts/json-to-seed.js from data/project-data.json.");
  lines.push("-- Do not hand-edit; re-run `npm run seed` to regenerate.");
  lines.push("-- updated_by / created_by = 'seed' marks the original import.");
  lines.push("");

  let pid = 0; // project id
  let oid = 0; // open_item id
  let hid = 0; // stage_history id
  let tid = 0; // timeline id
  let sort = 0; // global render order (group order preserved by GROUPS in assemble.js)

  for (const g of groups) {
    const groupKey = g.key; // 'dev' | 'ops'
    for (const p of g.projects || []) {
      pid += 1;
      const thisSort = sort;
      sort += 1;

      lines.push(`-- ${groupKey} / ${p.name}`);
      lines.push(
        "INSERT INTO projects " +
          '(id, "group", name, status, status_class, stage, stage_class, statusline, what_it_is, next_step, sort, updated_by) VALUES'
      );
      lines.push(
        `  (${pid}, ${sReq(groupKey)}, ${sReq(p.name)}, ${sReq(p.status)}, ` +
          `${p.statusClass ? sReq(p.statusClass) : "'info'"}, ` +
          `${s(p.stage)}, ${s(p.stageClass)}, ${s(p.statusline)}, ` +
          `${s(p.whatItIs)}, ${s(p.next)}, ${thisSort}, 'seed');`
      );

      let isort = 0;
      for (const it of p.openItems || []) {
        oid += 1;
        lines.push(
          "INSERT INTO open_items " +
            "(id, project_id, text, stage, stage_class, meta, sort, updated_by) VALUES"
        );
        lines.push(
          `  (${oid}, ${pid}, ${sReq(it.text)}, ${s(it.stage)}, ${s(it.stageClass)}, ` +
            `${sReq(it.meta)}, ${isort}, 'seed');`
        );
        isort += 1;
      }

      for (const h of p.stageHistory || []) {
        hid += 1;
        lines.push(
          "INSERT INTO stage_history (id, project_id, when_label, note, created_by) VALUES"
        );
        lines.push(`  (${hid}, ${pid}, ${sReq(h.when)}, ${sReq(h.note)}, 'seed');`);
      }

      for (const t of p.timeline || []) {
        tid += 1;
        lines.push(
          "INSERT INTO timeline (id, project_id, when_label, note, created_by) VALUES"
        );
        lines.push(`  (${tid}, ${pid}, ${sReq(t.when)}, ${sReq(t.note)}, 'seed');`);
      }

      lines.push("");
    }
  }

  return lines.join("\n") + "\n";
}

const data = JSON.parse(readFileSync(inPath, "utf8"));
const sql = build(data);
writeFileSync(outPath, sql, "utf8");
console.error(`Wrote ${outPath} (${sql.length} bytes) from ${inPath}`);
